// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sis_UserV2;

namespace Sis_UserV2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Sis_UserV2.Models.Auth_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Pass")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Auth_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.Doc_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<byte[]>("Doc")
                        .HasMaxLength(2147483647)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Doc_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.Endereco_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Bairro")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("CEP")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Cidade")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Estado")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Lote")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Quadra")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Rua")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Endereco_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.Fone_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("FoneCelular1")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("FoneCelular2")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("FoneFixo")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Fone_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.Image_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<byte[]>("Img")
                        .HasMaxLength(2147483647)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Image_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.Keyword_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("KeyWord")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Keyword_User");
                });

            modelBuilder.Entity("Sis_UserV2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CPF")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Email")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.Property<string>("RG")
                        .HasMaxLength(2147483647)
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
